### ISSUE TITLE
fbdev support for RK3328 ?

### ISSUE THREAD

**Issue by rtissera** [rockchip-linux/libmali#12]
Hello,

Would it be possible to have fbdev support for RK3328 on arm64 and armhf ?

It has been implemented by other vendors as linked here by ARM :
https://developer.arm.com/products/software/mali-drivers/user-space

**Comment by yanghanxing** [comment]
Yes,It can support.Will update later.

**Comment by rtissera** [comment]
Thanks for your answer, looking forward to it 👍 
DMA-BUF support and VSYNC on/off option would be amazing, as implemented by some other vendors.

**Comment by wzyy2** [comment]
fbdev mali have support DMA-BUF.
VSYNC is always off with fbdev.

**Comment by rtissera** [comment]
Ok. Hardkernel has implemented VSYNC on the top of fbdev, details on [this page](https://forum.odroid.com/viewtopic.php?f=7&t=14253)

This is very handy for games and emulators in order to avoid tearing.

**Comment by wzyy2** [comment]
Yeah, but we are mainly focused on GBM/KMS.
