### ISSUE TITLE
Older user-space drivers for RK3399?

### ISSUE THREAD

**Issue by achirkin** [rockchip-linux/libmali#13]
Hi, I have a somewhat unusual use case here.

Samsung Chromebook plus has RK3399 inside, and I enjoy using crouton (change root) with it. The latest ChromeOS also has wayland running on it (for android subsystem). Thus, it is possible and very convenient to run wayland applications from inside change root environment. Now, it would be great to make wayland applications running with hardware acceleration instead of using mesa software drivers. I tried using `libmali` drivers from inside Chrome OS, but they do not include wayland client code. Then I found this repository and tried `libmali-midgard-4th-r13p0-wayland.so` but got the error message:
```
ERROR: The DDK is not compatible with any of the Mali GPUs on the system.
The DDK was built for 0x860 r2p0 status range [0..15], but none of the GPUs matched:
file /dev/mali0 is not of a compatible version (user 10.4, kernel 10.2)
```
Since there is no way to update kernel space drivers without breaking the whole system, it would be really nice to find older user-space drivers.
So, my question is: what is the `rXXpX` package version of user-space drivers corresponding to kernel drivers 10.2? Do you have it with wayland support somewhere in you archives? :)

**Comment by wzyy2** [comment]
You can't get libmali-wayland  work in chroot.

**Comment by wzyy2** [comment]
To use wayland with hardware acceleration,  you need make chromebook boot with rockchip 4.4 kernel 
 + pure GNU/Linux rootfs.

**Comment by achirkin** [comment]
Could you please elaborate on this? What makes Chrome OS kernel incampatible with libmali-wayland? Given that wayland server is provided by OS and succesfully used in android subsystem, and the kernel is packed with (some version of) mali driver?

**Comment by wzyy2** [comment]
- -
It's not  **Chrome OS kernel incampatible with libmali-wayland**(of course, we also can't provide libmali with every version....), it's that **wayland with hardware acceleration** can't work with ChromeOS(Freon) by chroot.....

**Comment by achirkin** [comment]
Hmm, I am not an expert in this area. But as far as I understand, Current arm ChromeOS version does provide a wayland server capable of showing hardware accelerated clients, which is used in its android subsystem.
I conclude this because android games indeed run accelerated, because android rootfs does have some libraries named `wayland-service.so` inside, and because news about android-running-via-wayland appeared earlier this year (e.g. [on reddit](https://www.reddit.com/r/linux/comments/5n0yc3/having_some_fun_with_wayland_support_in_chromeos/)).

Though, all of this certainly does not make sense if you don't have `libmali-wayland` lib for that particular version of kernel drivers :(
