### ISSUE TITLE
xcb_dri3_pixmap_from_buffer on MPP decoded frame fails with BadAlloc due to gbm_bo_import returning NULL

### ISSUE THREAD

**Issue by ydirson** [rockchip-linux/libmali#14]
I'm trying to render MPP-decoded frames using DRI3+XPresent, as Xorg answers "yes I support those extensions".

My call basically looks like:

```
        MppBuffer buf = mpp_frame_get_buffer(frm);
        xcb_pixmap_t pixmap = xcb_generate_id(xcb);
        xcb_void_cookie_t cookie =
             xcb_dri3_pixmap_from_buffer_checked (xcb,
                                                 pixmap,
                                                 x11_window,
                                                 mpp_buffer_get_size(buf), // mesa uses 0?
                                                 mpp_buffer_get_width(frm),
                                                 mpp_buffer_get_height(frm),
                                                 mpp_buffer_get_stride(frm),
                                                 32, // FIXME depth
                                                 32, // bpp
                                                 mpp_buffer_get_fd(buf));
        xcb_generic_error_t *error;
        if ((error = xcb_request_check(xcb, cookie))) {
            fprintf(stderr, "dri3_pixmap_from_buffer failure: code=%d value=%d\n",
                    error->error_code, error->resource_id);
            free(error);
            return -1;
        }
```

I tried several values for depth and bpp, being quite unsure of what DRI3 expects since we're feeding it a NV12 buffer.  All attempts resulted in an ALLOC error. Using gdb I could trace it down until glamor_back_pixmap_from_fd which then calls libMali's gbm_bo_import and gets a failure:

```
#0  glamor_back_pixmap_from_fd (pixmap=pixmap@entry=0x55794ed6e0, fd=fd@entry=17, width=width@entry=1920, height=height@entry=1080, stride=stride@entry=1920, depth=depth@entry=32 ' ',
    bpp=bpp@entry=32 ' ') at ../../../../glamor/glamor_egl.c:576
#1  0x0000007f9a8bad24 in glamor_pixmap_from_fd (screen=0x5578ffc5d0, fd=17, width=1920, height=1080, stride=1920, depth=32 ' ', bpp=32 ' ') at ../../../../glamor/glamor_egl.c:590
#2  0x000000555707733c in dri3_pixmap_from_fd (ppixmap=0x7ffe368ce0, ppixmap@entry=0x7ffe368d10, screen=<optimized out>, fd=fd@entry=17, width=<optimized out>, height=<optimized out>,
    stride=<optimized out>, depth=<optimized out>, bpp=<optimized out>) at ../../dri3/dri3_screen.c:73
#3  0x0000005557076f3c in proc_dri3_pixmap_from_buffer (client=0x5579175470) at ../../dri3/dri3_request.c:162
#4  0x0000005556f48674 in Dispatch () at ../../dix/dispatch.c:431

(gdb) p import_data
$3 = {fd = 17, width = 1920, height = 1080, stride = 1920, format = 875713089}
```

I'm a bit worried about the ARGB8888 format, so I also tried to force it to 0x3231564E through gdb before the call, but that does not help.

Am I doing anything wrong, or is PRIME buffer import not supported yet by the Mali driver ?

**Comment by wzyy2** [comment]
I think that DRI3 isn't supported...... All those graphics things in X11 are for desktop platform and the gpu performance on X11 isn't very efficient.
If you have to render MPP-decoded frames on X11, then use OpenGL ES(fullscreen), or you can use wayland(dmabuf display/OpenGL ES) rather than X11.
DRM is also an optional though the video layer will always be on the top of the UI layer.

**Comment by wzyy2** [comment]
You should refer to our gstreamer solution..
It's hard to explain them.

**Comment by ydirson** [comment]
I'll be looking at the gstreamer display plugin closer.

I'm still puzzled as to why DRI3QueryVersion and DRI3Open would not return any error, if DRI3PixmapFromBuffer which is one the 2 core calls would not be implemented, I rather think I'm probably missing something (or maybe some lib support is missing?).

Also not that for decoding-buffer allocation I've implement both the "intermediate" approach seen in the decoder test and ffmpeg, and on the other side the more complicated one seen in gstreamer, and noted that the decoding time is 2-3 times better with the intermediate approach (this in itself could explain why Kodi is able to render 4K@60fps, although the bbb video is shaky at times, and gstreamer is completely unable to achieve the same).

**Comment by hizukiayaka** [comment]
I don't think the kodi would perform better than Gstreamer.
