### ISSUE TITLE
Kernel DDK mismatch

### ISSUE THREAD

**Issue by StuartIanNaylor** [rockchip-linux/libmali#16]
Kernel was updated DDK to r7p0-00rel1 whilst libmali has build for libmali-rk-utgard-450-r7p0.install

**Comment by wzyy2** [comment]
Did you encounter problems?
I think  `libmali-rk-utgard-450-r7p0.so` is also `r7p0-00rel1`.

**Comment by StuartIanNaylor** [comment]
Might be my build I am using the Rock64 ayufan builds and trying to start X11 but just ends with a seg fault.
Is it possible to load opengl es 2.0 with glamor yet with X11 or is that still WIP?

**Comment by wzyy2** [comment]
There is some bugs for utgard GPU to use glamor, and we don't plan to fix it... : (
You could use armsoc DDX if you want to use gles in X11.
