### ISSUE TITLE
rk3328 mali450 libmali-gbm

### ISSUE THREAD

**Issue by nikitos1550** [rockchip-linux/libmali#17]
Hello!

I am trying to use QT5 eglfs backend without X11/Wayland. 

I suppose that I have to choose library from these list:

- libmali-utgard-450-r7p0-fbdev.so 
- libmali-utgard-450-r7p0-gbm.so
- libmali-utgard-450-r7p0-wayland.so
- libmali-utgard-450-r7p0-x11-fbdev.so
- libmali-utgard-450-r7p0.so 	

I chosed libmali-utgard-450-r7p0-gbm.so
Made all links to it. Qt5 itself check and found 3 EGLFS implementations:

> EGLFS .................................. yes 
> EGLFS details: 
> EGLFS i.Mx6 .......................... no 
> EGLFS i.Mx6 Wayland .................. no 
> EGLFS EGLDevice ...................... yes 
> EGLFS GBM ............................ yes 
> EGLFS Mali ........................... yes 
> EGLFS Rasberry Pi .................... no 
> EGL on X11 ........................... no

No errors during compile time, but during runtime EGLFS is not working

```
# QT_QPA_DEBUG=1 QT_QPA_PLATFORM=eglfs QT_LOGGING_RULES="qt.qpa.*=true" ./analog
clock
qt.qpa.egldeviceintegration: EGL device integration plugin keys: ("eglfs_kms_egldevice", "eglfs_kms", "eglfs_mali")
qt.qpa.egldeviceintegration: EGL device integration plugin keys (sorted): ("eglfs_kms", "eglfs_kms_egldevice", "eglfs_mali")
qt.qpa.egldeviceintegration: Trying to load device EGL integration "eglfs_kms"
qt.qpa.egldeviceintegration: Failed to load EGL device integration "eglfs_kms"
qt.qpa.egldeviceintegration: Trying to load device EGL integration "eglfs_kms_egldevice"
qt.qpa.egldeviceintegration: Failed to load EGL device integration "eglfs_kms_egldevice"
qt.qpa.egldeviceintegration: Trying to load device EGL integration "eglfs_mali"
qt.qpa.egldeviceintegration: Using EGL device integration "eglfs_mali"
Could not open egl display
Aborted
```

Same time linuxfb is working fine. 
So how can I debug it? My kernel is rockchip version 4.4
libDRM is mainline 2.4.75 (I also used rockchip-libdrm, but same result and acording wiki seems it is outdated and I should use mainline). 

I also try EGLFS Mali via libmali-utgard-450-r7p0-fbdev.so, no success (I don`t know is it proper way or not).

Same time I build MPP proper way and it is working ok.

So, please point me proper way to use QT5 with EGLFS backend via KMS/GBM.

**Comment by nikitos1550** [comment]
P.S. of course I am using arm64 versions

**Comment by wzyy2** [comment]
Could you try yocto? https://github.com/rockchip-linux/meta-rockchip
I think qt-eglfs should work with yocto SDK.

**Comment by wzyy2** [comment]
1. Either, it doesn't matter.
2. Either, but master branch is possible to be broken, because of upstream changes.
3,4. You just need make sure "/dev/mali0" is exist.
5. No differences between them.

**Comment by nikitos1550** [comment]
I have /dev/mali, not /dev/mali0. Is it critical?

**Comment by wzyy2** [comment]
it's ok

**Comment by nikitos1550** [comment]
So, finally it got it working, build QT5 with static linking, because assumed that something was about dynamic linking, will determine problem later.
Now two questions:
I got this message 
`[   27.375758] devfreq ff300000.gpu: Couldn't update frequency transition information.`
**What is it about? What problems or special behaviour can I expect because of this?**

Second question, if HDMI display is not connected, I have such error:

```
 ./analogclock
[  246.006561] analogclock[249]: unhandled level 2 translation fault (11) at 0x00000008, esr 0x92000006
[  246.007420] pgd = ffffffc03632c000
[  246.007728] [00000008] *pgd=000000003632a003, *pud=000000003632a003, *pmd=0000000000000000
[  246.008501]
[  246.008643] CPU: 3 PID: 249 Comm: analogclock Not tainted 4.4.93 #1
[  246.009209] Hardware name: Rockchip RK3328 EVB (DT)
[  246.009642] task: ffffffc039898d00 task.stack: ffffffc03880c000
[  246.010173] PC is at 0x466680
[  246.010462] LR is at 0x46c6e4
[  246.010729] pc : [<0000000000466680>] lr : [<000000000046c6e4>] pstate: 60000000
[  246.011393] sp : 0000007ff3ea4630
[  246.011693] x29: 0000007ff3ea4630 x28: 0000000000000000
[  246.012197] x27: 0000000000000000 x26: 0000000000000000
[  246.012686] x25: 0000000000000000 x24: 0000000000000000
[  246.013171] x23: 00000000009ae028 x22: 0000000001646ee0
[  246.013681] x21: 00000000009a8f68 x20: 000000000075f3a8
[  246.014166] x19: 0000007ff3ea4768 x18: 0000000000000001
[  246.014673] x17: 0000007f895d9630 x16: 00000000009a3d18
[  246.015158] x15: ffffffffffffffff x14: 312d412d494d4448
[  246.015665] x13: ff00000000000000 x12: 0000000000000000
[  246.016151] x11: 0000000000000038 x10: 0000000001650fb0
[  246.016659] x9 : 0000007f896e8508 x8 : 0101010101010101
[  246.017145] x7 : 7f7f7f7f7f7f7f7f x6 : ff52514e53424045
[  246.017653] x5 : 0000000000000010 x4 : 0000000000000038
[  246.018138] x3 : 0053524f54434146 x2 : 0000007ff3ea4628
[  246.018644] x1 : 0000000000000001 x0 : 0000000000000000
[  246.019129]
Segmentation fault
```
Seems I have to check is display connected to my board or not before using anything related to gpu.
**What is the best way to check is display connected or not?** Also what is the proper way to determine capabilities of display (means which resolutions can I set to output).

**Comment by nikitos1550** [comment]
Also opengl is not working, 
```
qt.qpa.eglfs.kms: Creating window for screen "HDMI1"
EGL Error : Could not create the egl surface: error = 0x300b
```
0x300b is EGL_BAD_NATIVE_WINDOW. **Is it common error?**

**Comment by nikitos1550** [comment]
There are some patches in meta-rockchip for QT5, but them are not related to this issue, as I can see now. Will dig deeper...

**Comment by wzyy2** [comment]
Could you try old " libmali-utgard-2th-r7p0-gbm.so"?

**Comment by nikitos1550** [comment]
I already had try with  libmali-utgard-2th-r7p0-gbm.so and libmali-utgard-450-r7p0-gbm.so
I will build QT5 will full debug and try to see where EGL_BAD_NATIVE_WINDOW error appears exactly.
As I have searched internet it is common error, that can be because some EGL implementation defaults. But all advices I have found assume some old QT version, my version is 5.8.something and structure of elgfs sources is a bit different so, it will take time to dig.

**Comment by nikitos1550** [comment]
So, I solved all problems except opengl problem.
After some debugging found problem with 

```
void QEglFSWindow::resetSurface()
{
    EGLDisplay display = screen()->display();
    QSurfaceFormat platformFormat = qt_egl_device_integration()->surfaceFormatFor(window()->requestedFormat());

    m_config = QEglFSIntegration::chooseConfig(display, platformFormat);
    m_format = q_glFormatFromConfig(display, m_config, platformFormat);
    m_window = qt_egl_device_integration()->createNativeWindow(this, screen()->geometry().size(), m_format);
    m_surface = eglCreateWindowSurface(display, m_config, m_window, NULL);
}
```
 eglCreateWindowSurface returns error. Maybe there is some hook that change standard QT (by the way I am using 5.7.1 version) way of creating egl surface?

**Comment by armoreno** [comment]
I think you are using a user-space libMali that is not compatible with Qt5 EGLFS

**Comment by nikitos1550** [comment]
Hello @armoreno ! Yes, I am using  libmali-utgard-450-r7p0-gbm.so (that I took from this repo) that is user space lib as I understand. Qt5 eglfs has different backends, for example eglfs_kms (that uses libdrm and libgbm), eglfs_kms_egldevice (that uses only libdrm) and eglfs_mali (that uses framebuffer for access mali features as I understand). 

From your comment I can understand that there is some kernel space Mali driver, but of cource there is, also user space libMali assumes that there is kernel layer that will handle it.

Also, in this repo includes files there are EGL and FBDEV dirs, mostly it is same, but seems FBDEV assumes using /dev/fb, not /dev/dri/.... Somewhere here (https://github.com/rockchip-linux/libmali/issues/12)  I read that community focused on GBM/KMS, so I thought that I should use drm way.

So in QT i have two avalible eglfs implementations _kms and _kms_egldevice, _kms works ok, but no opengl, _kms_egldevice fails with **EGL_EXT_device_base missing**, I haven`t debug it, so don`t know is it really missing or is it my build mistake.

What is proper way to deploy all this to use non-X graphical enviroiment. There is **rk-qt-video** (https://github.com/rockchip-linux/rk-qt-video) repo, it is QtMultimedia implementation for rockchip and there is some example that also requires opengl, so I suppose somebody had it work.

**Comment by wzyy2** [comment]
Not sure if i have update wrong mali, that's why i ask you to try `libmali-utgard-2th-r7p0-gbm.so`.
We have test qt-eglfs for rk3328 in yocto before, using `libmali-utgard-2th-r7p0-gbm.so`, so i think you should try yocto.

**Comment by nikitos1550** [comment]
@wzyy2  Hello! I will try again **libmali-utgard-2th-r7p0-gbm.so** I will get it from https://github.com/ayufan-rock64/libmali/tree/rockchip-before-20171113/lib/aarch64-linux-gnu
What about includes? Which should I use? EGL or FBDEV?

**Comment by nikitos1550** [comment]
I checked again https://github.com/rockchip-linux/meta-rockchip according https://github.com/rockchip-linux/meta-rockchip/blob/master/dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%25.bbappend seems 
elgfs in this case used as X11 backend. Maybe I should try to use QT5 over X11 layer and opengl will work, I will try. Just wanted to avoid not necessary overhead of X11 before.

**Comment by wzyy2** [comment]
No... It means if both x11 and wayland is not used, enable eglfs

**Comment by nikitos1550** [comment]
I see, my mistake, sorry. So it should work with opengl without X. Got it. Still what is difference between EGL and FBDEV includes? Which should I use in which case?

**Comment by armoreno** [comment]
Hello @nikitos1550! According to my experience, you should to build Qt5 for using eglfs_mali (fbdev), because eglfs_kms is not fully supported, and eglfs_kms_egldevice is mainly focused to be used with the Tegra (NVIDIA) boards, so it doesn't work, too.

If you build Qt5 for using the EGLFS Mali plugin, so you will need to have access to /dev/fb or /dev/fb0 (but not /dev/dri/...). A good test would be to build the Mali SDK (https://developer.arm.com/products/software/mali-sdks/opengl-es) and try them, if those demos work fine, then Qt5 EGLFS Mali should work, too. 

Regarding to Mali user-space drivers, I referred that maybe you need to manually replace yours by the properly ones you can download from ARM (https://developer.arm.com/products/software/mali-drivers/user-space). At least that is I needed to do with my Ubuntu in order to get Qt5 EGLFS Mali working on a RK3288-Firefly board.
  
I agree with @wzyy2 about Qt5 EGLFS over X11 backend will not be a good choice...

About the includes I think EGL is the right one.

**Comment by wzyy2** [comment]
eglfs_kms  is supported. We have use it for a long time. It need `libmali-xxx-gbm.so`.
eglfs_mali is also supported, but we didn't test it. It need `libmali-xxx-fbdev.so`.

**Comment by armoreno** [comment]
Well, then I suppose eglfs_kms didn't work during my tests because I didn't selected the properly libmali.so (it means the libmali-xxx-gbm.so).

Thank you for the clarification.

**Comment by nikitos1550** [comment]
@wzyy2 @armoreno  Hello! Thank you very much! Seems opengl was not working, because I used some QT5 test that try to open opengl window not proper way, some other opengl tests works good with gbm/drm (libmali-...-gbm.so). I am not very familiar with details, will study it later, but seems it is limitation that while using eglfs you can create only one window, not several window contexts (as we can do with X or wayland), but I am not sure. I haven`t try libmali-...-fbdev.so yet.
My last question what is main difference between elgfs_mali and eglfs_kms backends, which should I prefer in which case?

**Comment by nikitos1550** [comment]
Seems everything is somehow clear. This issue can be close.
