### ISSUE TITLE
Vulkan drivers for RK3288

### ISSUE THREAD

**Issue by mmaldacker** [rockchip-linux/libmali#18]
Hello, are there vulkan drivers fro the RK3288?
Thanks!

**Comment by wzyy2** [comment]
:-P  No
You should ask arm guys, we also want to know when we can get a  vulkan driver for mali gpu on linux.

**Comment by JyuHo** [comment]
Everyone is sending the ball to the Vulkan drivers. At the latest news, ARM seems to say that they give you the permissions to do the said driver with the support of Vulkan, but a priori this is not what Rockchip would have understood from their answer. In any case ARM says that it is Rockchip to make the drivers with Vulkan support and that you have everything you need to do it. So what is Rockchip waiting for?

**Comment by danFromTelAviv** [comment]
ping. This is very significant to a lot of users. Is there any progress on this? 
https://community.arm.com/graphics/f/discussions/10218/future-drivers-with-vulkan-for-sbc-tinkerboard

**Comment by skyne98** [comment]
Same, ping @wzyy2, they seem to be providing the required drivers:
Kernel - https://developer.arm.com/products/software/mali-drivers/midgard-kernel
Userspace (Vulkan) - https://developer.arm.com/products/software/mali-drivers/user-space
