### ISSUE TITLE
wayland drivers missing nested compositor extension

### ISSUE THREAD

**Issue by mihailescu2m** [rockchip-linux/libmali#22]
midgard drivers (e.g. Rockchip T8xx r14) are missing nested compositor extension

I have notified ARM about this issue when I was testing mali T628 - which also has this issue  https://community.arm.com/graphics/f/discussions/9319/mali-eglinitialize-fails - but, since i am not a licensee and since T628 is too old, they probably won't fix this issue

i hope to see this fixed on RK t8xx - nested compositor is used by webkitgtk for accelerated (EGL) rendering; with it, gnome-web browser can use EGL for displaying content (webgl pages, pages with gstreamer plugin content - like youtube etc). Without it, it's all slow software rendering.

**Comment by wzyy2** [comment]
Is it a missing feature?

How about chromium-ozone-wayland? It might not use nested compositor.
https://github.com/OSSystems/meta-browser/blob/master/recipes-browser/chromium/chromium-ozone-wayland_64.0.3274.0.r517731.igalia.1.bb

**Comment by mihailescu2m** [comment]
Yes, it’s a missing feature (not implemented by arm).

Chromium is not using nested compositor, it has a different architecture. WebKitGTK sets itself up as a wayland server (within your wayland server), and all tabs become separate processes that are wayland EGL clients. Chromium has all within one process from what I’ve seen (when I had a tab crashing because GPU, the entire browser crashed).
