### ISSUE TITLE
wayland midgard drivers - egl objects release issue

### ISSUE THREAD

**Issue by mihailescu2m** [rockchip-linux/libmali#23]
this is another bug i have encountered with mali T628, which affects RK T8xx wayland drivers (and probably all midgard wayland drivers) - egl surface destroy somehow ends up crashing the entire app.

some EGL apps are not that affected (single windows ones - since the crash happens on app exit) but some others are unusable: for example, on chrome for wayland, opening up the chrome menu or a contextual menu (like right click on link) end up with chrome crashing after you select an option and the menu has to close (and the texture in the menu is destroyed).

ARM says it's GTK3's fault, but GTK devs say it's driver issue. Whoever's fault this is, it happens only on ARM mali systems, not on intel, nvidia, amd etc.

- https://community.arm.com/graphics/f/discussions/9338/mali-egldestroysurface-causes-segmentation-fault

- https://community.arm.com/graphics/f/discussions/8146/r12p0-wayland-driver-odroid-xu3-frees-objects-too-early-leading-to-segm-fault

**Comment by wzyy2** [comment]
Thanks for infos.

- -There are so many bugs in wayland-mali. 
I'm considering create a issue list to ARM, but at current we don't have dev plan on wayland.

**Comment by mihailescu2m** [comment]
@wzyy2 That’s too bad :(
Gnome3 on wayland is very fast and smooth, and with gnome 3.28 (in Ubuntu 18.04) should have all patches required to run on Mali out of the box. There are only a couple of big issues that affects many apps unfortunately...

**Comment by wzyy2** [comment]
Interesting.
Do you get gome-wayland work on rk3399? Can you share with me how to do it?

I did try it in debian-10, but it didn't work.

**Comment by mihailescu2m** [comment]
Debian 10 currently has gnome 3.26.2, which require only 1 small patch to make Mali work (there were many more patches required in Debian 9). I submitted the patch to 3.28 but it was also backported to 3.26.3, so the next mutter update should make Mali work on Debian too :)

**Comment by mihailescu2m** [comment]
Here you can find the patch: https://bugzilla.gnome.org/show_bug.cgi?id=780668
