### ISSUE TITLE
Mali T86x is missing DRM_FORMAT_NV12_10 support.

### ISSUE THREAD

**Issue by OtherCrashOverride** [rockchip-linux/libmali#26]
The current libmali-midgard-t86x-r14p0-x11-fbdev driver does not support DRM_FORMAT_NV12_10 as a color format argument in the ```eglCreateImageKHR``` feature support exposed by the ```EXT_image_dma_buf_import``` extension.

The format is defined by the kernel here:
https://github.com/rockchip-linux/kernel/blob/eae92ae2b930999857df47c3057327c1c490454b/include/uapi/drm/drm_fourcc.h#L119

**Comment by wzyy2** [comment]
DRM_FORMAT_NV12_10 is a rockchip defined format, of course it's not supportted by libmali.
