### ISSUE TITLE
Vulkan for tinkerboard (RK3288 mali T-764)

### ISSUE THREAD

**Issue by JyuHo** [rockchip-linux/libmali#30]
I did not know where to put this so I allow myself to do it on the Rockchip github.

I posted a request on the ARM forums about drivers with Vulkan embedded in it and this is what I was told:

>"Hi Jyu, 
>
>We don't provide binary drivers directly except for a small number of reference development platforms. Official drivers for any specific commercial chipset must be sourced from the chipset manufacturer, as they will typically need to integrate chip-specific aspects such as GPU power management which are outside of the GPU design we provide.
>
>Vulkan drivers supporting Mali-T760 are already available to our chipset providers to license, if they so desire.
>
>HTH, 
>Pete "

So I wanted to know if there was news about a future driver output incorporating Vulkan in your company? because ARM seems to have given you everything needed to be able to achieve them.

Best regards

Jyu

**Comment by dmschwartzii** [comment]
Did you get an answer
