### ISSUE TITLE
Latest releases of gnome/gtk3 (libclutter/libmutter) and wayland require libmali-wayland.so update

### ISSUE THREAD

**Issue by digitalsanity** [rockchip-linux/libmali#35]
Missing symbols like: gbm_bo_get_offset

/usr/bin/Xwayland: symbol lookup error: /usr/bin/Xwayland: undefined symbol gbm_bo_get_offset

gnome-shell: symbol lookup error: /usr/lib/aarch64-linux-gnu/libmutter-2.so.0: undefined symbol: gbm_surface_create_with_modifiers

**Comment by ah-** [comment]
I've also ran into this, with just pure Weston:

```
$ weston
Date: 2018-08-29 UTC
[17:39:44.415] weston 5.0.0
               https://wayland.freedesktop.org
               Bug reports to: https://gitlab.freedesktop.org/wayland/weston/issues/                                  
               Build: unknown (not built from git or tarball)                                                         
[17:39:44.415] Command line: weston
[17:39:44.415] OS: Linux, 4.18.0-rc8-1, #1 SMP PREEMPT Mon Aug 27 01:31:00 UTC 2018, aarch64                          
[17:39:44.416] Starting with no config file.
[17:39:44.416] Output repaint window is 7 ms maximum.
[17:39:44.416] Loading module '/usr/lib/libweston-5/drm-backend.so'                                                   
[17:39:44.438] Failed to load module: /usr/lib/libweston-5/drm-backend.so: undefined symbol: gbm_bo_get_offset        
[17:39:44.438] fatal: failed to create compositor backend
```

Is there any way of getting an updated driver?

**Comment by heiher** [comment]
Need too.

**Comment by heiher** [comment]
I have a way to fix this issue: https://hev.cc/2845.html

**Comment by Kwiboo** [comment]
@heiher nice, I created a similar gbm wrapper at https://github.com/LibreELEC/libmali/tree/master/src some time ago that worked well on Kodi, fortunately Kodi have introduced build checks/flags for the newer gbm api methods and made the use of a gbm wrapper unnecessary

**Comment by digitalsanity** [comment]
I was able to upgrade ayufan bionic to cosmic unstable for arm64 packages
of gnome/wayland/etc HEAD repos and get most/everything working and made
quite some progress with kwayland.  This patch on that gnome should make
for a working mali+wayland+gnome setup I think?

**Comment by ah-** [comment]
Nice! Great to see progress.

**Comment by JeffyCN** [comment]
normally you should recompile them with libmali's gbm.pc, they should detect gbm api version from pkgconfig and avoid using newer api.

but it's a great idea to support new api through wrapper library, and that should be done in the newest version now.
