### ISSUE TITLE
Bad SRC-URI for rockchip-mali

### ISSUE THREAD

**Issue by arajkovic** [rockchip-linux/libmali#37]
When running `bitbake qt5-image` following error occurs:
ERROR: rockchip-mali-rk-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1161"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/aca/rk-yocto-bsp/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/aca/rk-yocto-bsp/sources/poky/scripts:/home/aca/rk-yocto-bsp/build/tmp/work/cortexa17hf-neon-vfpv4-rk-linux-gnueabi/rockchip-mali/rk-r0/recipe-sysroot-native/usr/bin/arm-rk-linux-gnueabi:/home/aca/rk-yocto-bsp/build/tmp/work/cortexa17hf-neon-vfpv4-rk-linux-gnueabi/rockchip-mali/rk-r0/recipe-sysroot/usr/bin/crossscripts:/home/aca/rk-yocto-bsp/build/tmp/work/cortexa17hf-neon-vfpv4-rk-linux-gnueabi/rockchip-mali/rk-r0/recipe-sysroot-native/usr/sbin:/home/aca/rk-yocto-bsp/build/tmp/work/cortexa17hf-neon-vfpv4-rk-linux-gnueabi/rockchip-mali/rk-r0/recipe-sysroot-native/usr/bin:/home/aca/rk-yocto-bsp/build/tmp/work/cortexa17hf-neon-vfpv4-rk-linux-gnueabi/rockchip-mali/rk-r0/recipe-sysroot-native/sbin:/home/aca/rk-yocto-bsp/build/tmp/work/cortexa17hf-neon-vfpv4-rk-linux-gnueabi/rockchip-mali/rk-r0/recipe-sysroot-native/bin:/home/aca/rk-yocto-bsp/sources/poky/bitbake/bin:/home/aca/rk-yocto-bsp/build/tmp/hosttools"; export HOME="/home/aca"; /usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P /home/aca/rk-yocto-bsp/downloads/ 'https://github.com/rockchip-linux/libmali/raw/rockchip/lib/arm-linux-gnueabihf/libmali-midgard-t76x-r14p0-r0p0.so' --progress=dot -v failed with exit code 8, output:
--2018-08-27 18:44:43--  https://github.com/rockchip-linux/libmali/raw/rockchip/lib/arm-linux-gnueabihf/libmali-midgard-t76x-r14p0-r0p0.so
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-08-27 18:44:45 ERROR 404: Not Found.

ERROR: rockchip-mali-rk-r0 do_fetch: Fetcher failure for URL: 'https://github.com/rockchip-linux/libmali/raw/rockchip/lib/arm-linux-gnueabihf/libmali-midgard-t76x-r14p0-r0p0.so'. Unable to fetch URL from any source.
ERROR: rockchip-mali-rk-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/aca/rk-yocto-bsp/build/tmp/work/cortexa17hf-neon-vfpv4-rk-linux-gnueabi/rockchip-mali/rk-r0/temp/log.do_fetch.767
ERROR: Task (/home/aca/rk-yocto-bsp/sources/meta-rockchip/recipes-graphics/libgles/rockchip-mali_rk.bb:do_fetch) failed with exit code '1'

**Workarround:**
replacing SRC-URI
https://github.com/rockchip-linux/libmali/raw/rockchip/lib/${MALI_TUNE}/${MALI_NAME} 
with
https://github.com/rockchip-linux/libmali/tree/29mirror/lib/${MALI_TUNE}/${MALI_NAME}

**Comment by rbdavison** [comment]
Actually the workaround SRC_URL should be 
https://github.com/rockchip-linux/libmali/raw/29mirror/lib/${MALI_TUNE}/${MALI_NAME}
otherwise the downloaded library is a HTML file and you get errors like

| DEBUG: Executing shell function do_install
| not an ELF executable
| WARNING: /home/user/Rock64/build/tmp/work/aarch64-rk-linux/rockchip-mali/rk-r0/temp/run.do_install.30077:1 exit 1 from 'patchelf --set-soname "libEGL.so.1" /home/user/Rock64/build/tmp/work/aarch64-rk-linux/rockchip-mali/rk-r0/image//usr/lib/libMali.so'
| ERROR: Function failed: do_install (log file is located at /home/user/Rock64/build/tmp/work/aarch64-rk-linux/rockchip-mali/rk-r0/temp/log.do_install.30077)

**Comment by JeffyCN** [comment]
the old yocto layer is no longer supported.
