### ISSUE TITLE
Handling of headers for midgard

### ISSUE THREAD

**Issue by ydirson** [rockchip-linux/libmali#38]
In meta-rockchip, the rockchip-mali recipe only fetches the .so from this repo and not any headers that would match it. The mesa headers are used instead, and this has nasty consequences, of which a couple hit me already on a rk3399/x11 platform, and which I had (apparently wrongly) reported against meta-qt5:
* https://github.com/meta-qt5/meta-qt5/issues/101
* https://github.com/meta-qt5/meta-qt5/issues/102

Looks like both problems would be solved by having a -dev package shipping headers matching the .so.

However, I see this repo only seems to have GLES headers for utgard, and not for midgard.

Further more, include/midgard/CMakeLists.txt refers to non-existent arm/winsys_x11/, which would possibly be a problem too.

What's the full story here ?

**Comment by JeffyCN** [comment]
the old yocto layer is outdated,newer one should be fine.
