### ISSUE TITLE
HW rendering through x-server/opengl doesn't work

### ISSUE THREAD

**Issue by naseebpanghal** [rockchip-linux/libmali#39]
I have board with RK3288
GPU Info: 
Mali-T76x MP4 r0p0 0x0750﻿

By default system doesn't have any userspace mali library hence i tried with all below libraries under director /usr/lib/arm-linux-gnueabihf/
libmali-midgard-t76x-r14p0-r1p0-x11-fbdev.so
libmali-midgard-t76x-r14p0-r0p0-x11-fbdev.so
libmali-midgard-t76x-r13p0-r0p0.so
 libmali-rk-midgard-t76x-r14p0-r0p0.deb --> package file

updated all softlink (libGL, libEGL, libgbm) appropriately.
when i reboot system, display manager never started. 
Check /var/log/Xorg.0.log and found 
> Failed to load /usr/lib/xorg/modules/extensions/libglx.so: /usr/lib/xorg/modules/extensions/libglx.so: undefined symbol: glXGetProcAddressARB

I checked libmali-midgard-t76x-r13p0-r0p0.so with nm -D and it doesn't have glXGetProcAddressARB. Same /var/log/Xorg.0.log tells.

I checked dmesg, below is the version of Kernel Mali diriver

> [    6.477477] I : [File] : drivers/gpu/arm/mali400/mali/linux/mali_kernel_linux.c; [Line] : 414; [Func] : mali_module_init(); svn_rev_string_from_arm of this mali_ko is '-c2c22e1', rk_ko_ver is '5', built at '17:51:36', on 'Sep  9 2017'.
> [    6.477763] Mali: Mali device driver loaded

I am not able to find Mali kernel driver's compatible userspace library.

With original mesa libraries, Display Manager works properly but no hardware rendering, software rasterizer is used.(i checked with glxgears and es2gears) llvm is used.

**Comment by boblun** [comment]
libMali supports egl not GLX, you need the armsoc ddx driver for Xorg to support egl. 

Make sure the installed libs are for the right architecture, IE armhf for an armhf userland or aarch64 for aarch64 userland. 

Also check which libs es2* load with ldd  its likley they are finding mesa libs ahead of mali. 

Last of all use "export LD_DEBUG=libs; es2_info" to see how the link loader resolves your shared libraries.

**Comment by kingio** [comment]
@boblun i'm not supergood at linux, could you detail more the third point? (Also check which libs es2* load with ldd its likley they are finding mesa libs ahead of mali.) Which command is it?

**Comment by boblun** [comment]
Just run ldd /usr/bin/es2gears (or wherever your es2gears is installed) You will fetch list of libraries it is loading. Make sure they are all the Mali version.

You can also set the LDDEBUG  environment variable to "libs" and then run your app, the loader will print out information about the link-loading process (how the libraries were found) this can reveal where for example you have a 64bit app but 32 bit libraries.

On 2 January 2019 5:42:12 PM AWST, "Carlos Domínguez" <notifications@github.com> wrote:
>@boblun i'm not supergood at linux, could you detail more the third
>point? (Also check which libs es2* load with ldd its likley they are
>finding mesa libs ahead of mali.) Which command is it?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rockchip-linux/libmali/issues/39#issuecomment-450820697

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JeffyCN** [comment]
we are using xserver + glamor + gpu(gles) or xserver + exa + rga now.
