### ISSUE TITLE
Mali 450 EGL Doesn't  accept EGL_OPENGL_API argument to eglBindAPI

### ISSUE THREAD

**Issue by boblun** [rockchip-linux/libmali#40]
For EGL_VERSION: 1.4 Linux-r7p0-00rel0

Calling eglBindAPI(EGL_OPENGL_API)

Results in "Invalid argument" error which suggests that EGL_OPENGL_API is not supported, but Khronos say that EGL 1.4 implementations should support this API

Should libmali-utgard-450 support this API?

**Comment by JeffyCN** [comment]
not supported, only accept opengles api
