### ISSUE TITLE
Client GBM buffers don't render for a few frames after resize

### ISSUE THREAD

**Issue by rastermann** [rockchip-linux/libmali#44]
I was testing Enlightenment's Wayland compositor on my rockpro64. It all works pretty well except for one nasty issue. Resizing windows results in the windows disappearing for a few frames while they resize. It seems to be something messed up in the winsys/drm integration inside libmali. It's easy to see - just compile and install efl+e+terminology (so you have a wayland client worth talking about) and enable gl accel in both enlightenment and in elementary_config. Run enlightenment_start in a text login console and resize a window and watch it vanish while resizing until you stop.

See the following for some pre-canned build setups (for arch but just using the same meson build options + ninja will work on Debian too as long as you install the dependencies):

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=efl-git
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=enlightenment-git
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=terminology-git

**Comment by JeffyCN** [comment]
Please try the newest version r18p0(libmali and kernel).
If still repro, please re-open and upload your rootfs image(to google drive) and provide repro steps.
