### ISSUE TITLE
libmali Dependency problem

### ISSUE THREAD

**Issue by acbdef123** [rockchip-linux/libmali#48]
root@ubuntu:~# apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libglvnd-dev mesa-common-dev
The following NEW packages will be installed:
  libglvnd-dev
The following packages will be upgraded:
  mesa-common-dev
1 upgraded, 1 newly installed, 0 to remove and 218 not upgraded.
136 not fully installed or removed.
Need to get 0 B/562 kB of archives.
After this operation, 200 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 126730 files and directories currently installed.)
Preparing to unpack .../mesa-common-dev_18.2.8-0ubuntu0~18.04.2_arm64.deb ...
Unpacking mesa-common-dev:arm64 (18.2.8-0ubuntu0~18.04.2) over (18.0.5-0ubuntu0~18.04.1) ...
dpkg: error processing archive /var/cache/apt/archives/mesa-common-dev_18.2.8-0ubuntu0~18.04.2_arm64.deb (--unpack):
 trying to overwrite '/usr/include/KHR/khrplatform.h', which is also in package libmali-rk-dev:arm64 1.6-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../libglvnd-dev_1.0.0-2ubuntu2.2_arm64.deb ...
Unpacking libglvnd-dev:arm64 (1.0.0-2ubuntu2.2) ...
dpkg: error processing archive /var/cache/apt/archives/libglvnd-dev_1.0.0-2ubuntu2.2_arm64.deb (--unpack):
 trying to overwrite '/usr/lib/aarch64-linux-gnu/libEGL.so', which is also in package rockchip-mali-midgard14 1.6-1
Errors were encountered while processing:
 /var/cache/apt/archives/mesa-common-dev_18.2.8-0ubuntu0~18.04.2_arm64.deb

**Comment by JeffyCN** [comment]
libmali would not provide -dev package now.
