### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by FSet89** [rockchip-linux/libmali#49]
I downloaded the repository on my Rockpi4 board, how can I install it? There is no documentation available.

**Comment by smartwell** [comment]
yes, can some one talk about this?????????

**Comment by JeffyCN** [comment]
it's using meson build system now, so: meson install

**Comment by gusarg81** [comment]
Would be to to specify this somewhere of how to install (if not already).

**Comment by JeffyCN** [comment]
> Would be to to specify this somewhere of how to install (if not already).

We are using the standard meson, so please check meson's official webside for more details:
https://mesonbuild.com/Quick-guide.html
https://mesonbuild.com/Installing.html

Our engilish is not good, so writing documents is really painful for us :(
It would be very helpful if someone willing to make pull requests to help improving the documents ;)

**Comment by gusarg81** [comment]
Hi,

Yes, no problem! I am not English native either (but Spanish one).

I asked the need of more info basically because I just realized the existence of meson build system with this repo for the first time. Just maybe adding that needs to be build with meson in README will be enough :)

**Comment by Tryeellion** [comment]
Hi, there

I build a Debian with repo (https://github.com/rockchip-linux/rk-rootfs-build) for PX30 platform (arm64).

But some error will show while using glmark2-es2 as followed messages

rk-debug mali-ver=rsx-p0-1.2
rk-debug mali-ver=rsx-p0-1.2
Error: eglInitialize() failed with error: 0x3001
rk-debug mali-ver=rsx-p0-1.2
Error: eglInitialize() failed with error: 0x3001
Error: main: Could not initialize canvas

Also, the hardware acceleration is not enable on Chromium. (Just for software)

Or it's not supported to X11 session (http://opensource.rock-chips.com/wiki_Mali#RK3326)

So, should I update/install the libMali to enable it (by meson install manually)?

Thanks!

**Comment by JeffyCN** [comment]
Hi Tryeellion,

For x11-mali, it requires a X display with available dri2 proctol to finish eglInitialize().

My best guess would be something wrong during the dri2 of xserver.

Currently rockchip custom xserver supports dri2 in 2 ways:
1/ glamor accel(based on mali egl)
2/ exa accel(based on librga)

They are selected in the xorg conf like this one:
https://github.com/JeffyCN/meta-rockchip/blob/master/recipes-graphics/xorg-xserver/files/20-modesetting.conf#L4

So you can ether switch to glamor accel, or try to figure out why librga not working(library not present or something wrong in the kernel)

**Comment by Tryeellion** [comment]
> Hi Tryeellion,
> 
> For x11-mali, it requires a X display with available dri2 proctol to finish eglInitialize().
> 
> My best guess would be missing dri2.
> 
> Currently rockchip custom xserver supports dri2 in 2 ways:
> 1/ glamor accel(based on mali egl)
> 2/ exa accel(based on librga)
> 
> They are selected in the xorg conf like this one:
> https://github.com/JeffyCN/meta-rockchip/blob/master/recipes-graphics/xorg-xserver/files/20-modesetting.conf#L4
> 
> So you can ether switch to glamor accel, or try to figure out why librga not working(library not present or something wrong in the kernel cause missing /dev/rga)

Hi, Jeffy

Thanks for your comments :)
