### ISSUE TITLE
mali-t860 vulkan support

### ISSUE THREAD

**Issue by nzlionhevrt** [rockchip-linux/libmali#50]
Can I use vulkan with mali-t860? I have libvulkan, but I can't run any example. Maybe some tutorial available how to install and run vulkan app?

**Comment by mko-io** [comment]
It's a highly desirable feature, please provide Vulkan support

**Comment by JeffyCN** [comment]
the company only bought vulkan support for android platform(it's expensive)...so....

**Comment by mko-io** [comment]
It seems Panfrost is the only way to get Vulkan on Mali GPU, sad
