### ISSUE TITLE
G31 aarch64 binary blobs seems to be a debug blob

### ISSUE THREAD

**Issue by AreaScout** [rockchip-linux/libmali#52]
Hi and Hello

The G31 aarch64 binary blobs seems to be a debug blob (-g -O0) and normally they are slower than release builds, can we have new release builds ? It's for the new Odroid Go Adv.  hardware.

https://github.com/rockchip-linux/libmali/blob/master/lib/aarch64-linux-gnu/libmali-bifrost-g31-rxp0-gbm.so

It would also be cool to test the blobs with the compiler directive `-ffast-math`

And we would also be glad if the binary would support the `GL_EXT_buffer_storage` extension

Thank you in forward and best regards

**Comment by shantigilbert** [comment]
Just to mention that the arm (32bit) are as well the debug version, hopefully we could see release versions of both blobs soon as I agree with @AreaScout that this could make the HW seem to perform slower than it actually is. 

Thanks!

**Comment by JeffyCN** [comment]
The newest ones are release build:
libmali/lib/aarch64-linux-gnu# strings *g31*|grep -o "profile=[^ ]*"
profile=bx301a01b-release
profile=bx301a01b-release
profile=bx301a01b-release
profile=bx301a01b-release
profile=bx301a01b-release
profile=bx301a01b-release

**Comment by AreaScout** [comment]
Thank you so much ! :)

**Comment by shantigilbert** [comment]
> The newest ones are release build:
> libmali/lib/aarch64-linux-gnu# strings _g31_|grep -o "profile=[^ ]*"
> profile=bx301a01b-release
> profile=bx301a01b-release
> profile=bx301a01b-release
> profile=bx301a01b-release
> profile=bx301a01b-release
> profile=bx301a01b-release

Thank you, I guess the reason why we asked was because every time you call the lib it prints this
`rk-debug mali-ver=rsx-p0-1.0`

Not sure if that is intended and its just to show the version (for whatever reason) or if it is in fact an error or debug version.

**Comment by JeffyCN** [comment]
rk-debug probably means rockchip's debug log, you should check the profile settings :)

**Comment by shantigilbert** [comment]
Yep, was just explaining why we asked :)
