### ISSUE TITLE
Truncated libraries ...

### ISSUE THREAD

**Issue by kif** [rockchip-linux/libmali#55]
Dear  JeffyCN,

Thanks for maintaining the user-space Mali libraries.

I quickly tested the sources you uploaded a couple of hours ago and the binary `.so` in the repository look truncated:
```
dpkg -i libmali-midgard-t76x-r18p0-r0p0-x11-arm_1.9-1_armhf.deb
Selecting previously unselected package libmali-midgard-t76x-r18p0-r0p0-x11-arm:armhf.
(Reading database ... 222763 files and directories currently installed.)
Preparing to unpack libmali-midgard-t76x-r18p0-r0p0-x11-arm_1.9-1_armhf.deb ...
Unpacking libmali-midgard-t76x-r18p0-r0p0-x11-arm:armhf (1.9-1) ...
Setting up libmali-midgard-t76x-r18p0-r0p0-x11-arm:armhf (1.9-1) ...
Processing triggers for libc-bin (2.28-10) ...
ldconfig: file /usr/lib/mali/libmali.so.1 is truncated

ldconfig: file /usr/lib/mali/libmali.so is truncated

ldconfig: file /usr/lib/mali/libmali.so.1.9.0 is truncated

ldconfig: file /usr/lib/mali/libmali-midgard-t76x-r18p0-r0p0-x11.so is truncated

ldconfig: file /usr/lib/libmali.so.1 is truncated
```
I just did a checkout + dpkg-buildpackage. The device is Tinkerboard featuring RK3288 with an `armbian` distribution running debian10.

Cheers,

Jerome

**Comment by JeffyCN** [comment]
this is expected(due to a glibc issue which was fixed in glibc 2.31):
https://github.com/NixOS/patchelf/issues/44

anyway, the libs should still work since i put a symlink under /usr/lib/
