### ISSUE TITLE
after meson install, clinfo display no version infomation avaliable

### ISSUE THREAD

**Issue by cvidkal** [rockchip-linux/libmali#59]
after meson install, clinfo display no version infomation avaliable

`clinfo: /usr/local/lib/aarch64-linux-gnu/libOpenCL.so.1: no version information available (required by clinfo)
clinfo: relocation error: clinfo: symbol clGetPlatformIDs, version OPENCL_1.0 not defined in file libOpenCL.so.1 with link time reference`

and when I run my cl code,
some error appeared.

`Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
arm_release_ver of this libmali is 'r18p0-01rel0', rk_so_ver is '4'.arm_release_ver of this libmali is 'r18p0-01rel0', rk_so_ver is '4'.Error: Getting Device fail!`

**Comment by JeffyCN** [comment]
well, the first one is fixed in https://github.com/JeffyCN/mirrors/commit/07daee4e8a4c379b3f474dea4699e9779d3dc7b4

the second one says could not find the device(/dev/mali0), could be something wrong in the kernel or just permission issue
