### ISSUE TITLE
RK3399 Vulkan drivers

### ISSUE THREAD

**Issue by OtherCrashOverride** [rockchip-linux/libmali#6]
Currently, there are no Vulkan enabled drivers for the RK3399/Mali T-860.  Will these be provided?

**Comment by Miouyouyou** [comment]
That's actually a good question.

[The Mali Midgard r12p0 FBdev user-space drivers for Firefly RK3288 boards, provided by the official ARM Mali team on their website](https://developer.arm.com/-/media/Files/downloads/mali-drivers/user-space/firefly/malit76xr12p004rel0linux1fbdevtar.gz), actually include all the Vulkan symbols ([except the ones associated with X11 and Wayland windowing systems](https://community.arm.com/graphics/f/discussions/8470/mali-and-vulkan-on-linux-fbdev/29300#29300)).

Did the ARM guys sold you a DDK without Vulkan support or ... ?

**Comment by OtherCrashOverride** [comment]
Was a Vulkan enabled driver provided to resolve this issue?

**Comment by wzyy2** [comment]
No......

**Comment by OtherCrashOverride** [comment]
A bit more verbose explanation for the status change would be appreciated.

**Comment by sprhawk** [comment]
I have tried running ARM vulkan-sdk examples on RK3288 board with r12p0 fbdev driver

**Comment by OtherCrashOverride** [comment]
The RK3399 is 64bit and has a Mali T-8xx.  The RK3288 drivers are not applicable to this issue.

**Comment by sebastianfelipe** [comment]
Is there any update? Some vulkan support for a RK3399? Thanks!
