### ISSUE TITLE
midgard-t76x-r18p0-r1p0 doesn't work with glamor

### ISSUE THREAD

**Issue by amazingfate** [rockchip-linux/libmali#60]
I have a rk3288w board. In the latest rootfs, driver midgard-t76x-r18p0-r1p0 is installed and the default AccelMethod is exa. When I change exa to glamor Xorg can't start.  Installing driver midgard-t76x-r14p0-r1p0 instead  of midgard-t76x-r18p0-r1p0 can make Xorg start with glamor. Since deb of midgard-t76x-r14p0-r1p0 is removed from the repo [rk-rootfs-build](https://github.com/Caesar-github/rk-rootfs-build), I want to know which kernel can make driver midgard-t76x-r18p0-r1p0 work with glamor.

**Comment by JeffyCN** [comment]
The midgard r18 DDK only works with midgard r18 kernel driver:
kernel/drivers/gpu/arm/midgard/

So please update your kernel.
