### ISSUE TITLE
是否有rk3399 debian用的r18稳定版?（Is there any stable release of r18 for rk3399?）

### ISSUE THREAD

**Issue by wangg** [rockchip-linux/libmali#61]
请问目前有没有rk3399 debian用的libmali r18稳定版?

我们在rk3399的debian上用OpenCL进行深度学习模型推理时，linux sdk自带的r14版有很小概率会随机卡死
用这边的r18就没有卡死的问题了。

但是我看changelog上说这个r18是unstable?是不推荐用在生产环境的意思吗？贵司是否有发布过稳定版本呢？
如果没有，是否有发布的计划呢？

**Comment by JeffyCN** [comment]
The "unstable" is not about Midgard R18 DDK, but about the new way of integrating the mali related libraries.

You can surely use the current version for productions.
