### ISSUE TITLE
installing full graphics stack

### ISSUE THREAD

**Issue by kittycatto** [rockchip-linux/libmali#62]
Hello! That might be very stupid question, but what actually i need to start drivers properly? I installed that thing, also tried some dkmses and other things, but it do nothing, just falling back into llvmpipe.
The questions are:
1) what should i install?
2) what configs i should edit (xorg's maybe?)

BTW SoC is RK3399

**Comment by bart112233** [comment]
Look at this [script ](https://forum.armbian.com/topic/9272-development-rk3399-media-script/)- it's was worked for me (ubuntu 18.04 + small changes in install bash script)

**Comment by JeffyCN** [comment]
You can simply build and install the debian style packages(.deb), or use the prebuilt ones:
https://github.com/JeffyCN/rockchip_mirrors/tree/debian/packages/arm64/libmali

For xorg:
1/ needs the rockchip custom xserver
2/ use modesetting and enable glamor(or exa(based on rockchip librga)) to provide dri2(needed by mali x11): 
https://github.com/JeffyCN/rockchip_mirrors/blob/debian/overlay/etc/X11/xorg.conf.d/20-modesetting.conf#L5
