### ISSUE TITLE
ODroid XU4 support

### ISSUE THREAD

**Issue by MastaG** [rockchip-linux/libmali#64]
Hi, I've tried to add support for the ODroid XU3 and XU4 by adding ARM Mali wayland/gbm/drm user-space driver for XU3  (malit62xr12p004rel0linux1wayland.tar.gz ) from here: https://developer.arm.com/tools-and-software/graphics-and-gaming/mali-drivers/user-space
I've extracted the libmali.so and added it as: libmali/lib/arm-linux-gnueabihf/libmali-midgard-t62x-r12p0-wayland.so

I've build it with the following modification:
```
diff --git a/meson_options.txt b/meson_options.txt
index 8b2f44b..17ca8ed 100644
--- a/meson_options.txt
+++ b/meson_options.txt
@@ -1,13 +1,13 @@
 option('arch', type: 'combo', choices: ['auto', 'arm', 'armv7l', 'armhf', 'arm32', 'armv8', 'arm64', 'aarch64'],
        description: 'arch (default: auto)')
-option('gpu', type: 'string', value: 'midgard-t86x',
-       description: 'GPU name (default: midgard-t86x)')
-option('version', type: 'string', value: 'r18p0',
-       description: 'GPU version (default: r18p0)')
+option('gpu', type: 'string', value: 'midgard-t62x',
+       description: 'GPU name (default: midgard-t62x)')
+option('version', type: 'string', value: 'r12p0',
+       description: 'GPU version (default: r12p0)')
 option('subversion', type: 'string', value: 'none',
        description: 'subversion (default: none)')
 option('platform', type: 'combo', choices: ['x11', 'gbm', 'wayland', 'only-cl', 'dummy'],
-       value: 'x11', description: 'platform (default: x11)')
+       value: 'wayland', description: 'platform (default: wayland)')
 option('with-overlay', type: 'boolean', value: 'false',
        description: 'install overlay (default: false)')
 option('opencl-icd', type: 'boolean', value: 'true',
```

Now the libgbm.so.1 that's created from the gbm_wrapper contains all gbm_bo_ functions which are missing from the libmali.so driver (as it's very old).
However when I attempt to build and run Kodi it will tell me:
```
2021-01-19 08:24:28.264 T:1161    DEBUG <general>: CDRMUtils::DrmFbGetFromBo - failed to add framebuffer: Invalid argument (22)
2021-01-19 08:24:28.264 T:1161    ERROR <general>: CDRMAtomic::FlipPage - Failed to get a new FBO
```

So for some reason the wrapped functions aren't working?

**Comment by JeffyCN** [comment]
first of all, the mali user space driver can only work with the matched kernel driver, so please use glmark2-es2 and other test tools to make sure it work well.

DrmFbGetFromBo - failed to add framebuffer: Invalid argument (22)
<--- this looks like drmModeAddFB2(or drmModeAddFB) failed, and drm driver returns -EINVAL. maybe you can try to log the arguments there, or try to check the kernel drm logs which would be enabled by:
echo 0xff > /sys/module/drm/parameters/debug

**Comment by MastaG** [comment]
Hi @JeffyCN,

Thanks for the quick repsonse.
The problem was that Kodi was built against mesa's headers instead of the ones provided by this package.
After doing a full rebuild Kodi is working fine now and makes use of the libgbm wrapper :+1: 

Only I'm having trouble running gnome-shell on wayland using the libgbm wrapper, it seems to segfault.
Still trying to debug it.

Thanks for now!
