### ISSUE TITLE
Installs KHR/mali_khrplatform.h instead of KHR/khrplatform.h

### ISSUE THREAD

**Issue by glebm** [rockchip-linux/libmali#66]
This seems like a bug

Perhaps this header should be renamed on install?

**Comment by glebm** [comment]
Oh, I see that it's because of https://github.com/rockchip-linux/libmali/commit/83f8b828ef2d4272fe7b2133d8da9cd7f554ed54

Perhaps there should be an option to rename it? E.g. in my case I'm not use mesa at all

**Comment by glebm** [comment]
Nevermind, I simply copy it on install. Not a big deal for package maintainers to check for this

**Comment by JeffyCN** [comment]
this header should only be used by mali headers, others should not directly include it

**Comment by glebm** [comment]
I've noticed that PPSSPP includes it, and without libmesa there is nothing in the system to provide it

https://github.com/hrydgard/ppsspp/blob/1b843ef8ccc41f41e1437751712c816a6fef77b3/Common/GPU/OpenGL/GLCommon.h#L12

https://github.com/hrydgard/ppsspp/blob/a1964ca1a108b1340e54ae30262f317c9dd6999b/ext/glew/GL/eglew.h#L106

I guess this is a bug in PPSSPP?

**Comment by JeffyCN** [comment]
> I've noticed that PPSSPP includes it, and without libmesa there is nothing in the system to provide it
> 
> https://github.com/hrydgard/ppsspp/blob/1b843ef8ccc41f41e1437751712c816a6fef77b3/Common/GPU/OpenGL/GLCommon.h#L12
> 
> https://github.com/hrydgard/ppsspp/blob/a1964ca1a108b1340e54ae30262f317c9dd6999b/ext/glew/GL/eglew.h#L106
> 
> I guess this is a bug in PPSSPP?

right, checking the code seems like an old hack for nvdia. that might work for old mesa, but now all the EGL/GLES/GL providers might provide their own "khrplatform.h" with their own platform related stuffs. so mixing them is quite dangerous, i think they should use API related platform headers instead, for example:
GL/glext.h
GLES/glext.h
GLES2/gl2ext.h
GLES3/gl3ext.h
EGL/eglext.h
EGL/eglextchromium.h
EGL/eglmesaext.h

or at least:
EGL/eglplatform.h
GLES/glplatform.h
GLES2/gl2platform.h
GLES3/gl3platform.h

**Comment by JeffyCN** [comment]
looks like there still quite a few packages need this header, i've add an option(khr-header) to install it.

so basically we need to enable it when no mesa headers installed and disable it when mesa header exists.
