### ISSUE TITLE
gbm bifrost-g31 aarch64 gbm_bo_create crash

### ISSUE THREAD

**Issue by glebm** [rockchip-linux/libmali#67]
I'm trying to use libmali on on an odroidgoA-like device using aarch64 with the following settings:

```
-Dplatform=gbm -Dgpu=bifrost-g31 -Dversion=rxp0
```

I've noticed that it crashes in `gbm_bo_create` and added some printf debugging: https://github.com/glebm/libmali/commit/cc31a63900a0e82193f394a471ff51366c4ec7ce

```
===== gbm_bo_create width=16 height=16 format=34325241 usage=0000000a
==== bo_create not found!
```

At first I thought the symbol is missing from `libmali.so` but it does seem to be there:

```
$ host/aarch64-buildroot-linux-gnu/bin/objdump -T host/aarch64-buildroot-linux-gnu/sysroot/usr/lib64/libmali.so.1.9.0 | grep bo_create
00000000004e55e4 g    DF .text	0000000000000188  Base        gbm_bo_create
```

`libmali.so.1` is also linked into the binary:

```
$ host/aarch64-buildroot-linux-gnu/bin/readelf -d host/aarch64-buildroot-linux-gnu/sysroot/usr/bin/emulationstation | grep NEEDED | grep libmali
 0x0000000000000001 (NEEDED)             Shared library: [libmali.so.1]
```

and into `libgbm.so`:

```
$ host/aarch64-buildroot-linux-gnu/bin/readelf -d host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/libgbm.so | grep NEEDED | grep libmali
 0x0000000000000001 (NEEDED)             Shared library: [libmali.so.1]
```

**Comment by glebm** [comment]
Downgrading to the commit just before 7359b29cb9854808a57e818534f3ec78c2292fea fixes the issue!

**Comment by JeffyCN** [comment]
well, you can try to use ldd to check the depends and maybe print dlerror()

if still cannot figure it out, maybe upload your rootfs image(using google drive)

**Comment by JeffyCN** [comment]
and please also provide ld debug logs:
LD_DEBUG=all <test cmd> &> ld.log

**Comment by glebm** [comment]
ld.log: [ld.zip](https://github.com/rockchip-linux/libmali/files/5873550/ld.zip)

**Comment by JeffyCN** [comment]
this wrapper should work in 2 ways:
1/ for an app which is prebuilt with mesa
  app link to libgbm, libgbm link to libmali, so calling gbm_bo_create: libgbm wrapper -> libmali

2/ for an app which is build with libmali
  app link to libmali and libgbm, calling gbm_bo_create should directly goes to libmali

but according to the log:
       881:     symbol=gbm_bo_create;  lookup in file=/usr/lib64/libgbm.so.1 [0]
       881:     binding file /usr/lib64/libgbm.so.1 [0] to /usr/lib64/libgbm.so.1 [0]: normal symbol `gbm_bo_create'
<---the ld look up symbol in libgbm instead of libmali

       881:     symbol=dlsym;  lookup in file=/lib64/libdl.so.2 [0]
       881:     binding file /usr/lib64/libgbm.so.1 [0] to /lib64/libdl.so.2 [0]: normal symbol `dlsym'
       881:     symbol=gbm_bo_create;  lookup in file=/usr/lib64/libdrm.so.2 [0]
       881:     /usr/lib64/libgbm.so.1: error: symbol lookup error: undefined symbol: gbm_bo_create (fatal)
<---ld search libdrm only

i cannot repro this, could you upload your rootfs image?

**Comment by glebm** [comment]
https://uptobox.com/q6qixmicp8rt -- this is a batocera.linux image for odroidgoA and similar devices

**Comment by glebm** [comment]
Sorry, this is the wrong image (has an older libmali)
I'll rebuild one with the broken version

**Comment by glebm** [comment]
Full image: https://uptobox.com/c0yv7n7cndi8 (batocera-odroidgoa-30-20210127.img.gz)
Just the rootfs: https://uptobox.com/3m53ncd3ggfc (rootfs.squashfs)

An example binary is /usr/bin/emulationstation ([buildroot package](https://github.com/batocera-linux/batocera.linux/blob/7afc37b1feeae7665dc27ae2eb11653fe0b795de/package/batocera/emulationstation/batocera-emulationstation/batocera-emulationstation.mk))

**Comment by JeffyCN** [comment]
ok, checking the ld log again, i see what is going on here.
the app is actually using SDL2, which would try to dlopen libgbm with the usually depended libs libdrm:
sdl2-2.0.7# vi configure.in
                    gbm_lib=[`find_lib "libgbm.so.*" "$DRM_LIBS"`]

    handle = dlopen(sofile, RTLD_NOW|RTLD_LOCAL);
    loaderror = (char *) dlerror();
    if (handle == NULL) {
        SDL_SetError("Failed loading %s: %s", sofile, loaderror);
    }

       881: opening file=/usr/lib64/libgbm.so.1 [0]; direct_opencount=1

so it will missing the new depends of libmali...
seems like a bug there, i'll try to find a way to workaround it, maybe try to dlopen libmali in libgbm

**Comment by glebm** [comment]
Thanks so much for looking into this!

**Comment by JeffyCN** [comment]
uploaded:
https://github.com/rockchip-linux/libmali/commit/6141ad6e6f2d3eb38e7e0962f61b78510b2e2d2c

**Comment by glebm** [comment]
Fix confirmed! Thanks!
