### ISSUE TITLE
errors when install with dpkg

### ISSUE THREAD

**Issue by MCredbear** [rockchip-linux/libmali#68]
I downloaded the code and run dpkg-buildpackages,then when I was installing libmali-utgard-450-r7p0-x11_1.9-1_arm64.deb and libmali-utgard-450-r7p0-gbm_1.9-1_arm64.deb,it reported:
dpkg: regarding libmali-utgard-450-r7p0-x11_1.9-1_arm64.deb containing libmali-utgard-450-r7p0-x11:
 libmali-utgard-450-r7p0-x11 conflicts with libmali-utgard-450-r7p0-gbm
  libmali-utgard-450-r7p0-gbm (version 1.9-1) is present and unpacked but not configured.

dpkg: error processing archive libmali-utgard-450-r7p0-x11_1.9-1_arm64.deb (--install):
 conflicting packages - not installing libmali-utgard-450-r7p0-x11
Setting up libmali-utgard-450-r7p0-gbm (1.9-1) ...
Processing triggers for libc-bin (2.28-10) ...
/sbin/ldconfig: file /usr/lib/mali/libmali.so.1.9.0 is truncated

/sbin/ldconfig: file /usr/lib/mali/libmali-utgard-450-r7p0-gbm.so is truncated

/sbin/ldconfig: file /usr/lib/mali/libmali.so is truncated

/sbin/ldconfig: file /usr/lib/mali/libmali.so.1 is truncated

/sbin/ldconfig: file /usr/lib/libmali.so.1 is truncated

Errors were encountered while processing:
 libmali-utgard-450-r7p0-x11_1.9-1_arm64.deb

**Comment by MCredbear** [comment]
Add:
then I add --force-all in dpkg,then it reported:
root@redbear-laptop:/home/firefly# dpkg -i --force-all libmali-utgard-450-r7p0-gbm_1.9-1_arm64.deb libmali-utgard-450-r7p0-x11_1.9-1_arm64.deb  
(Reading database ... 54125 files and directories currently installed.)
Preparing to unpack libmali-utgard-450-r7p0-gbm_1.9-1_arm64.deb ...
Unpacking libmali-utgard-450-r7p0-gbm (1.9-1) over (1.9-1) ...
dpkg: regarding libmali-utgard-450-r7p0-x11_1.9-1_arm64.deb containing libmali-utgard-450-r7p0-x11:
 libmali-utgard-450-r7p0-x11 conflicts with libmali-utgard-450-r7p0-gbm
  libmali-utgard-450-r7p0-gbm (version 1.9-1) is present and unpacked but not configured.

dpkg: warning: ignoring conflict, may proceed anyway!
dpkg: regarding libmali-utgard-450-r7p0-x11_1.9-1_arm64.deb containing libmali-utgard-450-r7p0-x11:
 libmali-utgard-450-r7p0-gbm conflicts with libmali-utgard-450-r7p0-x11
  libmali-utgard-450-r7p0-x11 (version 1.9-1) is to be installed.

dpkg: warning: ignoring conflict, may proceed anyway!
Preparing to unpack libmali-utgard-450-r7p0-x11_1.9-1_arm64.deb ...
Unpacking libmali-utgard-450-r7p0-x11 (1.9-1) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libEGL.so.1', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libGLESv1_CM.so.1', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libGLESv2.so.2', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libMali.so.1', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libgbm.so.1', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libmali.so.1.9.0', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/pkgconfig/egl.pc', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/pkgconfig/gbm.pc', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/pkgconfig/glesv1_cm.pc', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/pkgconfig/glesv2.pc', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/pkgconfig/mali.pc', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/libmali.so.1', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libEGL.so', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libGLESv1_CM.so', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libGLESv2.so', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libMali.so', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libgbm.so', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libmali.so', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/mali/libmali.so.1', which is also in package libmali-utgard-450-r7p0-gbm 1.9-1
Setting up libmali-utgard-450-r7p0-gbm (1.9-1) ...
Setting up libmali-utgard-450-r7p0-x11 (1.9-1) ...
Processing triggers for libc-bin (2.28-10) ...
/sbin/ldconfig: file /usr/lib/mali/libmali-utgard-450-r7p0-gbm.so is truncated

/sbin/ldconfig: file /usr/lib/mali/libmali.so.1.9.0 is truncated

/sbin/ldconfig: file /usr/lib/mali/libmali-utgard-450-r7p0-x11.so is truncated

/sbin/ldconfig: file /usr/lib/mali/libmali.so is truncated

/sbin/ldconfig: file /usr/lib/mali/libmali.so.1 is truncated

/sbin/ldconfig: file /usr/lib/libmali.so.1 is truncated

**Comment by JeffyCN** [comment]
those mali packages are conflicted to each other, you can only install one of them at the same time(depends on which display service you are using)

**Comment by MCredbear** [comment]
> those mali packages are conflicted to each other, you can only install one of them at the same time(depends on which display service you are using)

so which one did you use in the media-rk3328 script?and how about the truncated libs?

**Comment by MCredbear** [comment]
> those mali packages are conflicted to each other, you can only install one of them at the same time(depends on which display service you are using)

其实我是因为你做的那个脚本用不了才想自己把那个脚本里的东西都重新做一遍。我的板子是firefly roc-rk3328-cc，能装rock64的armbian，但用你那个脚本的时候，xserver能装上，但是不论用哪个驱动都卡的一批。mpv-gdm看起来能用mpp驱动，但是播放的时候依旧cpu 100%，其它的东西因为依赖问题装都装不上。

**Comment by JeffyCN** [comment]
first of all, i have no idea what is that script, i've never used armbian. guessing you should discuss this issue there.

truncated logs are due to a bug in ldconfig, which has been fixed in glibc 2.31.
