### ISSUE TITLE
glmark-es2 error。arm_release_ver of this libmali is 'r18p0-01rel0', rk_so_ver is '4'

### ISSUE THREAD

**Issue by tccxy** [rockchip-linux/libmali#69]
hi：
   i use the rk3399 kernel version is the offical git repository  and stable-4.4-rk3399-linux branch
   use the file system is debian10 ,build by offical sdk
   use clinfo 
```
linaro@linaro-alip:~$ sudo clinfo
arm_release_ver of this libmali is 'r18p0-01rel0', rk_so_ver is '4'.Number of platforms
      1
  Platform Name                                   ARM Platform
  Platform Vendor                                 ARM
  Platform Version                                OpenCL 1.2 v1.r18p0-01rel0.5cb5681058e8e076ff89747c20c32578
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from_buffer cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory
  Platform Extensions function suffix             ARM

  Platform Name                                   ARM Platform
Number of devices                                 1
  Device Name                                     Mali-T860
  Device Vendor                                   ARM
  Device Vendor ID                                0x8602000
  Device Version                                  OpenCL 1.2 v1.r18p0-01rel0.5cb5681058e8e076ff89747c20c32578
  Driver Version                                  1.2
  Device OpenCL C Version                         OpenCL C 1.2 v1.r18p0-01rel0.5cb5681058e8e076ff89747c20c32578
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               4
  Max clock frequency                             5MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              4
  Preferred / native vector sizes
....
```
but use glmark-es2 show 
```
linaro@linaro-alip:~$ glmark2-es2
arm_release_ver of this libmali is 'r18p0-01rel0', rk_so_ver is '4'.arm_release_ver of this libmali is 'r18p0-01rel0', rk_so_ver is '4'.Error: eglInitialize() failed with error: 0x3001
arm_release_ver of this libmali is 'r18p0-01rel0', rk_so_ver is '4'.Error: eglInitialize() failed with error: 0x3001
Error: main: Could not initialize canvas
```
  Is there any other way to use glmark-es2 ??

thanks a lot

**Comment by JeffyCN** [comment]
for eglInitialize() with mali's x11 winsys, it depends on 2 things:
1/ valid x display
2/ x dri2(currently provided by x server's RGA based exa accel)

this kind of failure usually related to 2/, you may need to check the Xorg logs(/var/log/Xorg.0.log) for any error logs related to exa or RGA.

and we are mostly using the kernel's develop-4.4 branch now.

**Comment by tccxy** [comment]
ok, thanks ,i switch the kernel's develop-4.4 branch  and try

**Comment by vingoseu** [comment]
linaro@linaro-alip:~$ es2_info
arm_release_ver of this libmali is 'r18p0-01rel0', rk_so_ver is '4'.EGL_VERSION: 1.4 Midgard-"r18p0-01rel0"
EGL_VENDOR: ARM
EGL_EXTENSIONS:
    EGL_KHR_image_pixmap, EGL_KHR_partial_update, 
    EGL_EXT_image_dma_buf_import, EGL_KHR_config_attribs, EGL_KHR_image, 
    EGL_KHR_image_base, EGL_KHR_fence_sync, EGL_KHR_wait_sync, 
    EGL_KHR_gl_colorspace, EGL_KHR_get_all_proc_addresses, 
    EGL_IMG_context_priority, EGL_ARM_pixmap_multisample_discard, 
    EGL_ARM_implicit_external_sync, EGL_KHR_gl_texture_2D_image, 
    EGL_KHR_gl_renderbuffer_image, EGL_KHR_create_context, 
    EGL_KHR_surfaceless_context, EGL_KHR_gl_texture_cubemap_image, 
    EGL_EXT_create_context_robustness
EGL_CLIENT_APIS: OpenGL_ES
GL_VERSION: OpenGL ES 3.2 v1.r18p0-01rel0.5cb5681058e8e076ff89747c20c32578
GL_RENDERER: Mali-T860
GL_EXTENSIONS:
    GL_ARM_rgba8, GL_ARM_mali_shader_binary, GL_OES_depth24, 
    GL_OES_depth_texture, GL_OES_depth_texture_cube_map, 
    GL_OES_packed_depth_stencil, GL_OES_rgb8_rgba8, GL_EXT_read_format_bgra, 
    GL_OES_compressed_paletted_texture, GL_OES_compressed_ETC1_RGB8_texture, 
    GL_OES_standard_derivatives, GL_OES_EGL_image, GL_OES_EGL_image_external, 
    GL_OES_EGL_image_external_essl3, GL_OES_EGL_sync, GL_OES_texture_npot, 
    GL_OES_vertex_half_float, GL_OES_required_internalformat, 
    GL_OES_vertex_array_object, GL_OES_mapbuffer, 
    GL_EXT_texture_format_BGRA8888, GL_EXT_texture_rg, 
    GL_EXT_texture_type_2_10_10_10_REV, GL_OES_fbo_render_mipmap, 
    GL_OES_element_index_uint, GL_EXT_shadow_samplers, 
    GL_OES_texture_compression_astc, GL_KHR_texture_compression_astc_ldr, 
    GL_KHR_texture_compression_astc_hdr, 
    GL_KHR_texture_compression_astc_sliced_3d, GL_KHR_debug, 
    GL_EXT_occlusion_query_boolean, GL_EXT_disjoint_timer_query, 
    GL_EXT_blend_minmax, GL_EXT_discard_framebuffer, 
    GL_OES_get_program_binary, GL_OES_texture_3D, GL_EXT_texture_storage, 
    GL_EXT_multisampled_render_to_texture, GL_OES_surfaceless_context, 
    GL_OES_texture_stencil8, GL_EXT_shader_pixel_local_storage, 
    GL_ARM_shader_framebuffer_fetch, 
    GL_ARM_shader_framebuffer_fetch_depth_stencil, GL_ARM_mali_program_binary, 
    GL_EXT_sRGB, GL_EXT_sRGB_write_control, GL_EXT_texture_sRGB_decode, 
    GL_EXT_texture_sRGB_R8, GL_EXT_texture_sRGB_RG8, 
    GL_KHR_blend_equation_advanced, GL_KHR_blend_equation_advanced_coherent, 
    GL_OES_texture_storage_multisample_2d_array, GL_OES_shader_image_atomic, 
    GL_EXT_robustness, GL_EXT_draw_buffers_indexed, 
    GL_OES_draw_buffers_indexed, GL_EXT_texture_border_clamp, 
    GL_OES_texture_border_clamp, GL_EXT_texture_cube_map_array, 
    GL_OES_texture_cube_map_array, GL_OES_sample_variables, 
    GL_OES_sample_shading, GL_OES_shader_multisample_interpolation, 
    GL_EXT_shader_io_blocks, GL_OES_shader_io_blocks, 
    GL_EXT_tessellation_shader, GL_OES_tessellation_shader, 
    GL_EXT_primitive_bounding_box, GL_OES_primitive_bounding_box, 
    GL_EXT_geometry_shader, GL_OES_geometry_shader, 
    GL_ANDROID_extension_pack_es31a, GL_EXT_gpu_shader5, GL_OES_gpu_shader5, 
    GL_EXT_texture_buffer, GL_OES_texture_buffer, GL_EXT_copy_image, 
    GL_OES_copy_image, GL_EXT_color_buffer_half_float, 
    GL_EXT_color_buffer_float, GL_EXT_YUV_target, GL_OVR_multiview, 
    GL_OVR_multiview2, GL_OVR_multiview_multisampled_render_to_texture, 
    GL_KHR_robustness, GL_KHR_robust_buffer_access_behavior, 
    GL_EXT_draw_elements_base_vertex, GL_OES_draw_elements_base_vertex

**Comment by JeffyCN** [comment]
both glamor and exa are available.

for exa error, as replied before,  you may need to check the Xorg logs(/var/log/Xorg.0.log) for any error logs related to exa or RGA.
