### ISSUE TITLE
Mali 450 arm64 drivers

### ISSUE THREAD

**Issue by ayufan** [rockchip-linux/libmali#7]
I was looking forward for these drivers: https://github.com/rockchip-linux/libmali/commit/255218e3463e53c8547b33c0955beaf6b9223029, but they are not for ARM64, still arm32.

**Comment by wzyy2** [comment]
Yeah, you are right........
- -#

**Comment by ayufan** [comment]
@wzyy2 Will you be able to fix that? :)

**Comment by wzyy2** [comment]
fix it now
