### ISSUE TITLE
Asus twinker board OpenCL performance problem

### ISSUE THREAD

**Issue by Saikatsaha1996** [rockchip-linux/libmali#71]
Asus twinker board
Rockchip 3288
Mali T 760 Gpu
How can I slove it OpenCL gpu frequency showing only 5 mhz but Mali T 760 gpu frequency 650 mhz
Help wanted
![IMG_20210603_213829](https://user-images.githubusercontent.com/72664192/120784743-0b229680-c54a-11eb-8061-e4427a15d49b.jpg)

**Comment by JeffyCN** [comment]
The rockchip libmali is maintained by rockchip gpu team, they are unlikely to check github issues.

Please send mail to them for future support, e.g. chenzhen@rock-chips.com, hds@rock-chips.com, putin.li@rock-chips.com.

And maybe also CC me ;)

**Comment by Saikatsaha1996** [comment]
> The rockchip libmali is maintained by rockchip gpu team, they are unlikely to check github issues.
> 
> Please send mail to them for future support, e.g. [chenzhen@rock-chips.com](mailto:chenzhen@rock-chips.com), [hds@rock-chips.com](mailto:hds@rock-chips.com), [putin.li@rock-chips.com](mailto:putin.li@rock-chips.com).
> 
> And maybe also CC me ;)

Okay thank you for your response..
Actually it not issue... Just wante to know about OpenCL gpu frequency...

Thank you

**Comment by JeffyCN** [comment]
for gpu freq, it's controlled by the mali driver's devfreq, check:
/sys/class/devfreq/*gpu/

**Comment by Saikatsaha1996** [comment]
Ok ok I will try...
