### ISSUE TITLE
New symbols required for Xwayland

### ISSUE THREAD

**Issue by MastaG** [rockchip-linux/libmali#73]
Hi, after updating Fedora 35 I got ```xorg-x11-server-Xwayland-21.1.3-1``` which seems to require more recent gbm symbols.
When trying to run it it fails on: ```gbm_bo_get_fd_for_plane```
Could this be added to the stubs file as well?

**Comment by JeffyCN** [comment]
done, try:
https://github.com/JeffyCN/rockchip_mirrors/commit/2f395cdb3387dd388ddc215d88238f5d57974324

**Comment by MastaG** [comment]
Fixed!
Faster than lightning ;)
Gnome is working again!

**Comment by MastaG** [comment]
@JeffyCN  will you also open a PR ro merge it into this repository?

**Comment by JeffyCN** [comment]
due to compony policy, this git account is kind of unmaintained...
