### ISSUE TITLE
Outdated OpenCL headers

### ISSUE THREAD

**Issue by sakamoto-poteko** [rockchip-linux/libmali#9]
The OpenCL headers files report themselves as version 1.1 in https://github.com/rockchip-linux/libmali/blob/rockchip/include/CL/cl.h#L153
```cpp
/* OpenCL Version */
#define CL_VERSION_1_0                              1
#define CL_VERSION_1_1                              1
```

If you run `clinfo` with r13p0 driver, the reported version, however, is `OpenCL 1.2 v1.r13p0-00rel0-git(a4271c9).31ba04af2d3c01618138bef3aed66c2c`. I've checked the library symbols, the library DOES HAVE OpenCL 1.2 functions.

As you guys were just including vanilla Khronos OpenCL headers, I'll go ahead and update them with vanilla 1.2 headers. Just let me know if you guys are okay with it.

**Comment by wzyy2** [comment]
We just casually add the header..
It would be nice if you send a pull request.

**Comment by sakamoto-poteko** [comment]
Ref PR #10

**Comment by wzyy2** [comment]
Thx
